const RANDOM_WALK_DATA = {
  "last_updated": "2026-04-08 — BUILD COMPLETE. All 11 entries + 40 suggestions + landing page done.",
  "entries": [
    { "number": "001", "name": "GLP-1 Weight Loss Drugs", "status": "done", "chain_steps": 12, "chain_total": 12, "critical_steps": [0,1,2,3,4,5,6,8,10], "source_count": 17, "xy_summary": "Lizard venom research → $100B obesity drug market" },
    { "number": "002", "name": "The Transformer / Modern AI", "status": "done", "chain_steps": 14, "chain_total": 14, "critical_steps": [0,1,2,3,4,5,6,7,8,9,10,11,12,13], "source_count": 18, "xy_summary": "Machine translation research → foundation of the AI revolution" },
    { "number": "003", "name": "mRNA Vaccines", "status": "done", "chain_steps": 13, "chain_total": 13, "critical_steps": [0,1,3,4,5,7,8,9,10,12], "source_count": 13, "xy_summary": "Decades of rejected grants → COVID vaccines in 11 months" },
    { "number": "004", "name": "The Internet", "status": "done", "chain_steps": 14, "chain_total": 14, "critical_steps": [0,1,2,3,4,5,6,7,9,10,11,12,13], "source_count": 13, "xy_summary": "Cold War nuclear survival → global information network" },
    { "number": "005", "name": "CRISPR Gene Editing", "status": "done", "chain_steps": 11, "chain_total": 11, "critical_steps": [0,1,2,5,6,7,9,10], "source_count": 12, "xy_summary": "Weird bacterial DNA repeats → programmable gene editing" },
    { "number": "006", "name": "Penicillin", "status": "done", "chain_steps": 11, "chain_total": 11, "critical_steps": [0,2,4,5,6,7,8,9], "source_count": 9, "xy_summary": "Contaminated petri dish → first antibiotic" },
    { "number": "007", "name": "Viagra", "status": "done", "chain_steps": 7, "chain_total": 7, "critical_steps": [2,3,4,6], "source_count": 5, "xy_summary": "Failed angina drug → $2B erectile dysfunction treatment" },
    { "number": "008", "name": "Lithium for Bipolar Disorder", "status": "done", "chain_steps": 8, "chain_total": 8, "critical_steps": [2,4,5,6,7], "source_count": 5, "xy_summary": "Guinea pigs injected with urine → psychiatry's most important drug" },
    { "number": "009", "name": "Microwave Oven", "status": "done", "chain_steps": 7, "chain_total": 7, "critical_steps": [2,3,6], "source_count": 5, "xy_summary": "WWII radar magnetrons → household cooking appliance" },
    { "number": "010", "name": "Teflon (PTFE)", "status": "done", "chain_steps": 7, "chain_total": 7, "critical_steps": [1,3,5], "source_count": 5, "xy_summary": "Refrigerant gas research → nonstick coatings & aerospace" },
    { "number": "011", "name": "Post-it Notes", "status": "done", "chain_steps": 7, "chain_total": 7, "critical_steps": [0,3,5,6], "source_count": 5, "xy_summary": "Failed strong adhesive → $1B office product" }
  ],
  "suggestions": [
    {"name":"Vulcanized Rubber","done":true},{"name":"Cardiac Pacemaker","done":true},{"name":"X-Rays","done":true},{"name":"Saccharin","done":true},{"name":"Safety Glass","done":true},{"name":"Velcro","done":true},{"name":"Radioactivity","done":true},{"name":"Super Glue","done":true},{"name":"Pulsars","done":true},{"name":"Cosmic Microwave Background","done":true},{"name":"GPS","done":true},{"name":"Graphene","done":true},{"name":"Checkpoint Inhibitor Immunotherapy","done":true},{"name":"Blue LEDs","done":true},{"name":"Kevlar","done":true},{"name":"Warfarin","done":true},{"name":"Nylon","done":true},{"name":"LSD","done":true},{"name":"Stainless Steel","done":true},{"name":"Minoxidil (Rogaine)","done":true},{"name":"Silly Putty","done":true},{"name":"Chlorpromazine","done":true},{"name":"Buckminsterfullerene","done":true},{"name":"Mauveine (First Synthetic Dye)","done":true},{"name":"Azole Antifungals","done":true},{"name":"Imatinib (Gleevec)","done":true},{"name":"Nitrous Oxide Anesthesia","done":true},{"name":"Positron (Antimatter)","done":true},{"name":"Integrated Circuit","done":true},{"name":"Lithium-Ion Battery","done":true},{"name":"Cisplatin","done":true},{"name":"Monte Carlo Method","done":true},{"name":"Dopamine & Parkinson's","done":true},{"name":"Radiocarbon Dating","done":true},{"name":"Optogenetics","done":true},{"name":"fMRI","done":true},{"name":"Haber-Bosch (Synthetic Fertilizer)","done":true},{"name":"AlphaFold","done":true},{"name":"GANs","done":true},{"name":"High-Temp Superconductors","done":true}
  ]
};
