// Visualization tags for all 51 random walk entries
// Dimensions: funding_source, origin/outcome fields (granular + category), institution_type, geography
// This file is separate from entries.js — used only for visualization overlays.

const VIZ_TAGS = [
  // === 11 Deep Entries ===
  { number: "001", name: "GLP-1 Weight Loss Drugs",
    funding_sources: ["NIH", "Veterans Administration"],
    origin_field: "Venom Biology", origin_category: "Biology & Life Sciences",
    outcome_field: "Pharmacology", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["Government Lab", "University"],
    geography_origin: "US", geography_outcome: "US / Denmark",
    era: "1967–2024", mechanism: "cross_pollination" },

  { number: "002", name: "The Transformer / Modern AI",
    funding_sources: ["Google", "CIFAR", "NSERC", "DARPA"],
    origin_field: "Consumer Internet", origin_category: "Computing & AI",
    outcome_field: "Artificial Intelligence", outcome_category: "Computing & AI",
    outcome_industry: "Tech",
    institution_types: ["Corporation", "University", "Nonprofit"],
    geography_origin: "US / Canada", geography_outcome: "Global",
    era: "1957–2024", mechanism: "tool_migration" },

  { number: "003", name: "mRNA Vaccines",
    funding_sources: ["Hungarian Academy of Sciences", "NIH", "DARPA", "BioNTech"],
    origin_field: "RNA Biochemistry", origin_category: "Biology & Life Sciences",
    outcome_field: "Vaccines & Immunology", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["University", "Corporation"],
    geography_origin: "Hungary / US", geography_outcome: "Global",
    era: "1978–2020", mechanism: "salvaged_failure" },

  { number: "004", name: "The Internet",
    funding_sources: ["DARPA", "NSF", "US Military"],
    origin_field: "Nuclear Survivability", origin_category: "Military & Defense",
    outcome_field: "Networking & Communications", outcome_category: "Computing & AI",
    outcome_industry: "Tech",
    institution_types: ["Government Lab", "University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1957–1995", mechanism: "tool_migration" },

  { number: "005", name: "CRISPR Gene Editing",
    funding_sources: ["Japanese Ministry of Education", "Spanish Ministry of Education", "NIH", "HHMI"],
    origin_field: "Microbiology", origin_category: "Biology & Life Sciences",
    outcome_field: "Genetics & Genomics", outcome_category: "Biology & Life Sciences",
    outcome_industry: "Biotech",
    institution_types: ["University"],
    geography_origin: "Japan / Spain", geography_outcome: "US / Global",
    era: "1987–2012", mechanism: "cross_pollination" },

  { number: "006", name: "Penicillin",
    funding_sources: ["British War Office", "Medical Research Committee", "Rockefeller Foundation", "US/UK Gov"],
    origin_field: "Bacteriology", origin_category: "Biology & Life Sciences",
    outcome_field: "Antibiotics", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["University", "Government Lab"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "1928–1945", mechanism: "accident" },

  { number: "007", name: "Viagra",
    funding_sources: ["Pfizer"],
    origin_field: "Heart Drug Development", origin_category: "Medicine & Drug Development",
    outcome_field: "Sexual Health", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["Corporation"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "1989–1998", mechanism: "side_effect" },

  { number: "008", name: "Lithium for Bipolar Disorder",
    funding_sources: ["Australian State Hospital"],
    origin_field: "Uric Acid Research", origin_category: "Biology & Life Sciences",
    outcome_field: "Psychiatry", outcome_category: "Neuroscience & Brain",
    outcome_industry: "Pharma",
    institution_types: ["Government Lab"],
    geography_origin: "Australia", geography_outcome: "Global",
    era: "1949–1970", mechanism: "accident" },

  { number: "009", name: "Microwave Oven",
    funding_sources: ["US Military", "Raytheon"],
    origin_field: "Radar Technology", origin_category: "Military & Defense",
    outcome_field: "Consumer Appliances", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1945–1967", mechanism: "accident" },

  { number: "010", name: "Teflon (PTFE)",
    funding_sources: ["DuPont"],
    origin_field: "Refrigerant Research", origin_category: "Chemistry & Materials",
    outcome_field: "Advanced Materials", outcome_category: "Chemistry & Materials",
    outcome_industry: "Materials / Aerospace",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1938–1960s", mechanism: "accident" },

  { number: "011", name: "Post-it Notes",
    funding_sources: ["3M"],
    origin_field: "Adhesive R&D", origin_category: "Chemistry & Materials",
    outcome_field: "Office Products", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1968–1980", mechanism: "salvaged_failure" },

  // === 40 Suggestion Entries ===
  { number: "012", name: "Vulcanized Rubber",
    funding_sources: ["Personal / Self-funded"],
    origin_field: "Industrial Chemistry", origin_category: "Chemistry & Materials",
    outcome_field: "Advanced Materials", outcome_category: "Chemistry & Materials",
    outcome_industry: "Transportation / Industry",
    institution_types: ["Independent Inventor"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "salvaged_failure" },

  { number: "013", name: "Cardiac Pacemaker",
    funding_sources: ["University of Buffalo"],
    origin_field: "Electrical Engineering", origin_category: "Engineering",
    outcome_field: "Cardiology Devices", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Medical Devices",
    institution_types: ["University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "salvaged_failure" },

  { number: "014", name: "X-Rays",
    funding_sources: ["University of Würzburg"],
    origin_field: "Cathode Ray Research", origin_category: "Physics & Astronomy",
    outcome_field: "Medical Imaging", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Medical Devices",
    institution_types: ["University"],
    geography_origin: "Germany", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "015", name: "Saccharin",
    funding_sources: ["Johns Hopkins"],
    origin_field: "Coal Tar Chemistry", origin_category: "Chemistry & Materials",
    outcome_field: "Food Additives", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "016", name: "Safety Glass",
    funding_sources: ["Personal / Self-funded"],
    origin_field: "Lab Chemistry", origin_category: "Chemistry & Materials",
    outcome_field: "Automotive Safety", outcome_category: "Consumer & Industrial",
    outcome_industry: "Transportation / Industry",
    institution_types: ["Independent Inventor"],
    geography_origin: "France", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "017", name: "Velcro",
    funding_sources: ["Personal / Self-funded"],
    origin_field: "Nature Observation", origin_category: "Biology & Life Sciences",
    outcome_field: "Fasteners & Textiles", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Independent Inventor"],
    geography_origin: "Switzerland", geography_outcome: "Global",
    era: "pre-1950", mechanism: "analogy" },

  { number: "018", name: "Radioactivity",
    funding_sources: ["French Academy of Sciences"],
    origin_field: "Fluorescence Research", origin_category: "Physics & Astronomy",
    outcome_field: "Nuclear Physics", outcome_category: "Physics & Astronomy",
    outcome_industry: "Energy / Medicine",
    institution_types: ["University"],
    geography_origin: "France", geography_outcome: "Global",
    era: "pre-1950", mechanism: "salvaged_failure" },

  { number: "019", name: "Super Glue",
    funding_sources: ["Eastman Kodak", "US Military"],
    origin_field: "Weapons Optics", origin_category: "Military & Defense",
    outcome_field: "Adhesives", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "salvaged_failure" },

  { number: "020", name: "Pulsars",
    funding_sources: ["UK Science Research Council"],
    origin_field: "Radio Astronomy", origin_category: "Physics & Astronomy",
    outcome_field: "Astrophysics", outcome_category: "Physics & Astronomy",
    outcome_industry: "Science",
    institution_types: ["University"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "1950-2000", mechanism: "accident" },

  { number: "021", name: "Cosmic Microwave Background",
    funding_sources: ["Bell Labs / AT&T"],
    origin_field: "Telecom Engineering", origin_category: "Engineering",
    outcome_field: "Cosmology", outcome_category: "Physics & Astronomy",
    outcome_industry: "Science",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "accident" },

  { number: "022", name: "GPS",
    funding_sources: ["US Navy", "DARPA", "US Military"],
    origin_field: "Military Navigation", origin_category: "Military & Defense",
    outcome_field: "Civilian Navigation", outcome_category: "Computing & AI",
    outcome_industry: "Tech",
    institution_types: ["Government Lab"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "analogy" },

  { number: "023", name: "Graphene",
    funding_sources: ["EPSRC", "University of Manchester"],
    origin_field: "Solid State Physics", origin_category: "Physics & Astronomy",
    outcome_field: "Nanomaterials", outcome_category: "Chemistry & Materials",
    outcome_industry: "Materials / Aerospace",
    institution_types: ["University"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "post-2000", mechanism: "tool_migration" },

  { number: "024", name: "Checkpoint Inhibitor Immunotherapy",
    funding_sources: ["NIH", "Howard Hughes"],
    origin_field: "Immunology", origin_category: "Biology & Life Sciences",
    outcome_field: "Cancer Treatment", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "cross_pollination" },

  { number: "025", name: "Blue LEDs",
    funding_sources: ["Nichia Corporation"],
    origin_field: "Semiconductor R&D", origin_category: "Engineering",
    outcome_field: "Lighting Technology", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Corporation"],
    geography_origin: "Japan", geography_outcome: "Global",
    era: "1950-2000", mechanism: "salvaged_failure" },

  { number: "026", name: "Kevlar",
    funding_sources: ["DuPont"],
    origin_field: "Polymer R&D", origin_category: "Chemistry & Materials",
    outcome_field: "Protective Materials", outcome_category: "Military & Defense",
    outcome_industry: "Defense / Aerospace",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "salvaged_failure" },

  { number: "027", name: "Warfarin",
    funding_sources: ["USDA", "University of Wisconsin"],
    origin_field: "Veterinary Pathology", origin_category: "Agriculture & Food",
    outcome_field: "Blood Thinners", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "cross_pollination" },

  { number: "028", name: "Nylon",
    funding_sources: ["DuPont"],
    origin_field: "Polymer R&D", origin_category: "Chemistry & Materials",
    outcome_field: "Synthetic Textiles", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "029", name: "LSD",
    funding_sources: ["Sandoz"],
    origin_field: "Alkaloid Chemistry", origin_category: "Chemistry & Materials",
    outcome_field: "Psychiatry", outcome_category: "Neuroscience & Brain",
    outcome_industry: "Pharma",
    institution_types: ["Corporation"],
    geography_origin: "Switzerland", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "030", name: "Stainless Steel",
    funding_sources: ["British Military"],
    origin_field: "Weapons Metallurgy", origin_category: "Military & Defense",
    outcome_field: "Advanced Materials", outcome_category: "Chemistry & Materials",
    outcome_industry: "Materials / Aerospace",
    institution_types: ["Government Lab"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "031", name: "Minoxidil (Rogaine)",
    funding_sources: ["Upjohn"],
    origin_field: "Heart Drug Development", origin_category: "Medicine & Drug Development",
    outcome_field: "Hair Loss Treatment", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "side_effect" },

  { number: "032", name: "Silly Putty",
    funding_sources: ["GE", "US Military"],
    origin_field: "Synthetic Rubber", origin_category: "Military & Defense",
    outcome_field: "Toys", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "salvaged_failure" },

  { number: "033", name: "Chlorpromazine",
    funding_sources: ["French Navy", "Rhône-Poulenc"],
    origin_field: "Surgical Anesthesia", origin_category: "Medicine & Drug Development",
    outcome_field: "Psychiatry", outcome_category: "Neuroscience & Brain",
    outcome_industry: "Pharma",
    institution_types: ["Government Lab", "Corporation"],
    geography_origin: "France", geography_outcome: "Global",
    era: "1950-2000", mechanism: "side_effect" },

  { number: "034", name: "Buckminsterfullerene",
    funding_sources: ["NSF", "Rice University"],
    origin_field: "Stellar Chemistry", origin_category: "Physics & Astronomy",
    outcome_field: "Nanomaterials", outcome_category: "Chemistry & Materials",
    outcome_industry: "Materials / Aerospace",
    institution_types: ["University"],
    geography_origin: "US / UK", geography_outcome: "Global",
    era: "1950-2000", mechanism: "analogy" },

  { number: "035", name: "Mauveine (First Synthetic Dye)",
    funding_sources: ["Royal College of Chemistry"],
    origin_field: "Malaria Drug Research", origin_category: "Medicine & Drug Development",
    outcome_field: "Synthetic Dyes", outcome_category: "Consumer & Industrial",
    outcome_industry: "Consumer Goods",
    institution_types: ["University"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "pre-1950", mechanism: "salvaged_failure" },

  { number: "036", name: "Azole Antifungals",
    funding_sources: ["ICI", "Janssen Pharmaceutica"],
    origin_field: "Crop Fungicides", origin_category: "Agriculture & Food",
    outcome_field: "Antifungal Drugs", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["Corporation"],
    geography_origin: "Belgium / UK", geography_outcome: "Global",
    era: "1950-2000", mechanism: "cross_pollination" },

  { number: "037", name: "Imatinib (Gleevec)",
    funding_sources: ["Novartis", "NIH"],
    origin_field: "Cell Signaling Research", origin_category: "Biology & Life Sciences",
    outcome_field: "Cancer Treatment", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["Corporation", "University"],
    geography_origin: "Switzerland / US", geography_outcome: "Global",
    era: "post-2000", mechanism: "cross_pollination" },

  { number: "038", name: "Nitrous Oxide Anesthesia",
    funding_sources: ["Pneumatic Institution"],
    origin_field: "Gas Experiments", origin_category: "Chemistry & Materials",
    outcome_field: "Anesthesia", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Medical Devices",
    institution_types: ["Nonprofit"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "039", name: "Positron (Antimatter)",
    funding_sources: ["Caltech", "NSF"],
    origin_field: "Cosmic Ray Research", origin_category: "Physics & Astronomy",
    outcome_field: "Particle Physics", outcome_category: "Physics & Astronomy",
    outcome_industry: "Science",
    institution_types: ["University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "accident" },

  { number: "040", name: "Integrated Circuit",
    funding_sources: ["Texas Instruments", "US Military"],
    origin_field: "Military Electronics", origin_category: "Military & Defense",
    outcome_field: "Semiconductor Industry", outcome_category: "Computing & AI",
    outcome_industry: "Tech",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "analogy" },

  { number: "041", name: "Lithium-Ion Battery",
    funding_sources: ["Exxon", "Oxford University", "Sony"],
    origin_field: "Oil Industry R&D", origin_category: "Energy",
    outcome_field: "Battery Technology", outcome_category: "Energy",
    outcome_industry: "Energy / Medicine",
    institution_types: ["Corporation", "University"],
    geography_origin: "US / UK / Japan", geography_outcome: "Global",
    era: "1950-2000", mechanism: "cross_pollination" },

  { number: "042", name: "Cisplatin",
    funding_sources: ["NIH", "Michigan State University"],
    origin_field: "Bacterial Electrophysics", origin_category: "Biology & Life Sciences",
    outcome_field: "Cancer Treatment", outcome_category: "Medicine & Drug Development",
    outcome_industry: "Pharma",
    institution_types: ["University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "salvaged_failure" },

  { number: "043", name: "Monte Carlo Method",
    funding_sources: ["US Military", "Los Alamos"],
    origin_field: "Nuclear Weapons R&D", origin_category: "Military & Defense",
    outcome_field: "Computational Methods", outcome_category: "Computing & AI",
    outcome_industry: "Tech",
    institution_types: ["Government Lab"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "analogy" },

  { number: "044", name: "Dopamine and Parkinson's",
    funding_sources: ["Swedish Research Council"],
    origin_field: "Basic Pharmacology", origin_category: "Medicine & Drug Development",
    outcome_field: "Neurotransmitter Science", outcome_category: "Neuroscience & Brain",
    outcome_industry: "Pharma",
    institution_types: ["University"],
    geography_origin: "Sweden", geography_outcome: "Global",
    era: "1950-2000", mechanism: "side_effect" },

  { number: "045", name: "Radiocarbon Dating",
    funding_sources: ["University of Chicago", "US Military"],
    origin_field: "Cosmic Ray Research", origin_category: "Physics & Astronomy",
    outcome_field: "Archaeological Dating", outcome_category: "Consumer & Industrial",
    outcome_industry: "Science",
    institution_types: ["University"],
    geography_origin: "US", geography_outcome: "Global",
    era: "pre-1950", mechanism: "analogy" },

  { number: "046", name: "Optogenetics",
    funding_sources: ["Humboldt University", "NIH", "Stanford"],
    origin_field: "Algae Biology", origin_category: "Biology & Life Sciences",
    outcome_field: "Neural Control Tools", outcome_category: "Neuroscience & Brain",
    outcome_industry: "Biotech",
    institution_types: ["University"],
    geography_origin: "Germany / US", geography_outcome: "Global",
    era: "post-2000", mechanism: "tool_migration" },

  { number: "047", name: "fMRI",
    funding_sources: ["Bell Labs / AT&T"],
    origin_field: "Blood Oxygenation Studies", origin_category: "Biology & Life Sciences",
    outcome_field: "Brain Imaging", outcome_category: "Neuroscience & Brain",
    outcome_industry: "Medical Devices",
    institution_types: ["Corporation"],
    geography_origin: "US", geography_outcome: "Global",
    era: "1950-2000", mechanism: "cross_pollination" },

  { number: "048", name: "Haber-Bosch Process",
    funding_sources: ["German Military", "BASF"],
    origin_field: "Explosives Chemistry", origin_category: "Military & Defense",
    outcome_field: "Synthetic Fertilizer", outcome_category: "Agriculture & Food",
    outcome_industry: "Agriculture",
    institution_types: ["Corporation", "Government Lab"],
    geography_origin: "Germany", geography_outcome: "Global",
    era: "pre-1950", mechanism: "tool_migration" },

  { number: "049", name: "AlphaFold",
    funding_sources: ["Google / DeepMind"],
    origin_field: "Game-Playing AI", origin_category: "Computing & AI",
    outcome_field: "Protein Structure Prediction", outcome_category: "Biology & Life Sciences",
    outcome_industry: "Biotech",
    institution_types: ["Corporation"],
    geography_origin: "UK", geography_outcome: "Global",
    era: "post-2000", mechanism: "tool_migration" },

  { number: "050", name: "GANs",
    funding_sources: ["CIFAR", "Université de Montréal"],
    origin_field: "Machine Learning", origin_category: "Computing & AI",
    outcome_field: "Generative AI", outcome_category: "Computing & AI",
    outcome_industry: "Tech",
    institution_types: ["University", "Nonprofit"],
    geography_origin: "Canada", geography_outcome: "Global",
    era: "post-2000", mechanism: "analogy" },

  { number: "051", name: "High-Temp Superconductors",
    funding_sources: ["IBM"],
    origin_field: "Ceramic Physics", origin_category: "Physics & Astronomy",
    outcome_field: "Superconductor Research", outcome_category: "Physics & Astronomy",
    outcome_industry: "Energy / Medicine",
    institution_types: ["Corporation"],
    geography_origin: "Switzerland", geography_outcome: "Global",
    era: "1950-2000", mechanism: "salvaged_failure" }
];
